# Generated by Django 3.2.2 on 2022-07-21 08:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pockets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цели')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Общая сумма цели')),
                ('now_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма цели в настоящий момент')),
                ('term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок в месяцах')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата создания цели')),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Ставка в процентах')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pockets.transactioncategory', verbose_name='Категория цели')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='TargetUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма обновления цели')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата обновления суммы цели')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='targets.target', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Обновление баланса цели',
                'verbose_name_plural': 'Обновляния баланса цели',
            },
        ),
    ]
