# Generated by Django 3.2.2 on 2022-07-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='now_amount',
        ),
    ]
