# Generated by Django 3.2.2 on 2022-07-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
        ('targets', '0002_remove_target_now_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pockets.transactioncategory', verbose_name='Категория цели'),
        ),
    ]
