# Generated by Django 3.2.2 on 2022-07-22 08:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_alter_target_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='start_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма начального взноса'),
            preserve_default=False,
        ),
    ]
