# Generated by Django 3.2.2 on 2022-07-22 08:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
        ('targets', '0004_target_start_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pockets.transactioncategory', verbose_name='Категория цели'),
        ),
        migrations.AlterField(
            model_name='target',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ставка в процентах'),
        ),
    ]
