# Generated by Django 3.2.2 on 2022-07-22 10:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_auto_20220722_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetupdate',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='target',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ставка в процентах'),
        ),
        migrations.AlterField(
            model_name='target',
            name='start_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма начального взноса'),
        ),
    ]
