# Generated by Django 3.2.2 on 2022-07-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0006_auto_20220722_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='start_date',
            new_name='create_date',
        ),
    ]
