# Generated by Django 3.2.2 on 2022-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0008_rename_create_date_target_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
