# Generated by Django 3.2.2 on 2022-07-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_target_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='complete',
            new_name='is_complete',
        ),
    ]
