# Generated by Django 3.2.2 on 2022-07-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0010_rename_complete_target_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
