# Generated by Django 3.2.2 on 2022-07-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0011_target_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetupdate',
            name='is_percent',
            field=models.BooleanField(default=False),
        ),
    ]
